# This is a generated file. Not intended for manual editing.
services:
  sportsrideklubskovly.api:
    build:
      context: "C:\\Dev\\Rider\\SportsRidingClubSkovly"
      dockerfile: "SportsRideKlubSkovly.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/SportsRideKlubSkovly.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "sportsrideklubskovly.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\danie\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Dev\\Rider\\SportsRidingClubSkovly\\SportsRideKlubSkovly.API:/app:rw"
    - "C:\\Dev\\Rider\\SportsRidingClubSkovly:/src:rw"
    working_dir: "/app"
