services:
  reverseproxy.api:
    build:
      context: ./ReverseProxy.API
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    environment:
      ASPNETCORE_HTTP_PORTS: 9000
    depends_on:
      sportsrideklubskovly.api:
        condition: service_started
    networks:
      - frontend
      - backend
  
  sportsrideklubskovly.api:
    image: sportsrideklubskovly.api
    build:
      context: ./SportsRideKlubSkovly.API
      dockerfile: Dockerfile
    environment:
      "ConnectionStrings:DefaultConnection": "Server=db;Database=SportsRidingClubSkovlyDB;MultipleActiveResultSets=true;TrustServerCertificate=true;User Id=SA;Password=StrongPassword123."
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
    networks:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:latest
    volumes:
      - C:\Dev\SQL\SportsRidingClubSkovlyDB:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123."
    ports:
      - "8090:1433" 
    networks:
      - backend
        
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge